.coverage_job:
  extends:
  - .rules:merge_request_pipelines:no_docs:always
  stage: coverage

test coverage report:
  extends:
  - .coverage_job
  coverage: /regular total:\s+\(statements\)\s+\d+.\d+\%/
  needs:
  - unit test
  - integration test
  script:
  - make cobertura_report
  - splitic junit-check -quarantined ci/.test-failures.servercore1809.txt .splitic/junit_servercore1809_*.xml
  - splitic junit-check -quarantined ci/.test-failures.servercore2004.txt .splitic/junit_servercore2004_*.xml
  - splitic junit-check -quarantined ci/.test-failures.servercore20H2.txt .splitic/junit_servercore20H2_*.xml
  artifacts:
    reports:
      cobertura: out/cobertura/cobertura-coverage.xml
    paths:
    - out/coverage/
    expire_in: 7d
    expose_as: 'Code Coverage'

#race conditions detector:
#  extends:
#  - .coverage_job
#  needs:
#  - unit test with race
#  - integration test with race
#  script:
#  - source ci/touch_make_dependencies
#  - make check_race_conditions

code navigation: # See https://docs.gitlab.com/ee/user/project/code_intelligence.html#configuration
  extends:
  - .coverage_job
  allow_failure: true # recommended
  needs:
  - prepare done
  image: sourcegraph/lsif-go:v1.3.1
  script:
  - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif
