trigger UBI images build:
  stage: postrelease
  variables:
    BUILD_RELEASE: ${CI_COMMIT_REF_NAME}
  trigger: gitlab-org/ci-cd/gitlab-runner-ubi-images
  only:
    refs:
    - main@gitlab-org/gitlab-runner
    - /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\Z/@gitlab-org/gitlab-runner

trigger runner-incept tests:
  extends:
    - .merge_request_pipelines
    - .except_docs
  stage: postrelease
  trigger: gitlab-org/ci-cd/tests/runner-incept
  needs:
    - 'bleeding edge docker images'
  only:
    refs:
      - main@gitlab-org/gitlab-runner
      - /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\Z/@gitlab-org/gitlab-runner
